### ISSUE TITLE
New issues with connecting SoundCloud account

### ISSUE THREAD

**Issue by Psyclop** [superturboryan/WatchCloud#3]
New customer. Same issue as spacecowboy. 

After successfully using WatchCloud for a long time, I have been asked to connect it tot the account again (this happened before a number of times with no issues).

However when I try to connect to the app on my phone, I do get an error message.

![IMG_9326](https://github.com/user-attachments/assets/88344ead-582e-47eb-bf30-69e8f640458d)

All other attempts to connect via AppleId or gmail also failed.

The issue has been recurring for the past few days.

**Comment by superturboryan** [comment]
Thanks for reaching out! 

Can you please confirm which version of the app you're using (1.3.1 or 1.3.2)? 

It should be in the top left corner of the About page which can be accessed by clicking the "i" in the top right of the screenshot.

As well as which watchOS version and Apple Watch model you're using, this may help me to diagnose your issue.

![IMG_569E9E5166D4-1](https://github.com/user-attachments/assets/3f5dba86-e558-481d-aeeb-1e6c2dcc2d7d)

**Comment by Psyclop** [comment]
It’s running 1.3.1 and was installed 2 days ago.

**Comment by Psyclop** [comment]
WatchOS version is 10.6

thanks

**Comment by Psyclop** [comment]
iOS version is 17.7

**Comment by Psyclop** [comment]
I’m seeing app version 1.3.2 released today. You want me to give version a go?

**Comment by superturboryan** [comment]
@Psyclop yes, please let me know if that fixes the issue with logging in. Thanks!

**Comment by superturboryan** [comment]
@Psyclop has the issue been occurring for a few days or was that part also copied from spacecowboy's post?

**Comment by Psyclop** [comment]
I started using the app 2 days ago so thats as far back as I can provide detail. But yeah, it’s been happening on and off the past 2 days.

I will give the update a try and report back on the experience. 😁

**Comment by Psyclop** [comment]
Installed version 1.3.2 and the error message is gone for now.

Should I open a new ticket to solve the issue related to the app always going back to showing “Connect to Sound” as not connected? So for example I open Watchcloud, connect to Soundcloud, close Watchcloud, re-open Watchcloud and it will show not connected even thought I just connected to Soundcloud.
![IMG_9331](https://github.com/user-attachments/assets/691d11b9-463d-4e9a-a591-90d942ff14fe)
![IMG_9332](https://github.com/user-attachments/assets/5d9a6ec6-bde9-46d4-8b0c-855a7f9c4b6c)

**Comment by superturboryan** [comment]
Thanks for confirming, @Psyclop ! 🤝

No need to raise another issue here for the iOS app not recognising that the watch app is already "connected". I'm already aware of this issue but there aren't plans to fix it atm
